ext {
    extName = 'box'
    extClass = '.Box'
    extVersionCode = 76
}

apply plugin: "kei.plugins.extension.legacy"

android {
    buildTypes {
        release {
            proguardFiles(
                rootProject.file("common/proguard-rules.pro"),
                file("proguard-rules.pro"),
            )
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    implementation(project(":lib:playlistutils"))
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs_nio:2.1.5")
    implementation("com.github.teamnewpipe:NewPipeExtractor:v0.26.4")
    implementation("org.mozilla:rhino:1.7.14")
}
